# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development do
  gem "minitest", "~> 5.20"
  gem "rake", "~> 13.0"
  gem "rubocop", require: false
  gem "rubocop-minitest", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rake", require: false
  gem "ruby-lsp", require: false
end
