# ruby/test/test_producer.rb
#
# frozen_string_literal: true

require_relative "test_helper"

FIXTURES = JSON.parse(File.read(FIXTURES_PATH, encoding: "UTF-8"))

HEART  = "❤️"
SOURCE = "Written by a human. Generated by AI."

class TestProducerFixtures < Minitest::Test
  def test_mark_cases
    FIXTURES["producer_cases"].each do |c|
      opts = c["options"]
      got = Textprov.mark(c["input"], state: opts["state"], mode: opts["mode"])

      assert_equal c["output"], got, "producer_case #{c["name"].inspect}"
    end
  end

  def test_convert_cases
    FIXTURES["convert_cases"].each do |c|
      opts = c["options"]
      got = Textprov.convert(c["input"], opts["from"], opts["to"])

      assert_equal c["output"], got, "convert_case #{c["name"].inspect}"
    end
  end
end

class TestProducerProperties < Minitest::Test
  def test_obsolete_states_are_rejected
    %w[mixed edited unknown].each do |state|
      %w[vs pua].each do |mode|
        ["", "abc"].each do |text|
          assert_raises(ArgumentError) { Textprov.mark(text, state: state, mode: mode) }
          assert_raises(ArgumentError) { Textprov.mark_added(text, text, state: state, mode: mode) }
          assert_raises(ArgumentError) { Textprov.mark_added("", text, state: state, mode: mode) }
        end
      end
    end
  end

  def test_strip_undoes_mark
    %w[vs pua].each do |mode|
      Textprov::GENERATED_STATES.each do |state|
        marked = Textprov.mark(SOURCE, state: state, mode: mode)

        assert_equal SOURCE, Textprov.strip_marks(marked), "state=#{state} mode=#{mode}"
      end
    end
  end

  # Rule 4 on input that already carries marks: the input itself cannot come
  # back, but its text does.
  def test_mark_changes_marks_never_text
    m = Textprov.default_mapping
    ai = m.selectors["ai"].chr(Encoding::UTF_8)
    human = m.selectors["human"].chr(Encoding::UTF_8)
    pua_a = m.base2pua["A".ord].chr(Encoding::UTF_8)
    [
      "A#{human}B", "A#{ai}B", "#{ai}A", "A#{ai}#{ai}", "A #{ai}B", "#{pua_a}B", "\u06001#{ai}2"
    ].each do |text|
      %w[vs pua].each do |mode|
        Textprov::GENERATED_STATES.each do |state|
          marked = Textprov.mark(text, state: state, mode: mode)

          assert_equal Textprov.strip_marks(text), Textprov.strip_marks(marked),
                       "text=#{text.inspect} state=#{state} mode=#{mode}"
        end
      end
    end
  end

  def test_mark_is_idempotent
    %w[vs pua].each do |mode|
      once = Textprov.mark(SOURCE, state: "ai", mode: mode)

      assert_equal once, Textprov.mark(once, state: "ai", mode: mode), "mode=#{mode}"
    end
  end

  def test_mark_does_not_touch_the_other_encoding
    pua = Textprov.mark(SOURCE, state: "ai", mode: "pua")

    assert_equal pua, Textprov.mark(pua, state: "ai", mode: "vs")
  end

  def test_pua_mode_equals_mark_then_convert
    vs = Textprov.mark(SOURCE, state: "ai", mode: "vs")

    assert_equal Textprov.convert(vs, "vs", "pua"), Textprov.mark(SOURCE, state: "ai", mode: "pua")
  end

  def test_convert_round_trips
    vs  = Textprov.mark(SOURCE, state: "ai", mode: "vs")
    pua = Textprov.convert(vs, "vs", "pua")

    refute_equal vs, pua
    assert_equal vs, Textprov.convert(pua, "pua", "vs")
  end

  def test_convert_passes_other_states_through
    marked = Textprov.mark(SOURCE, state: "human", mode: "vs")

    assert_equal marked, Textprov.convert(marked, "vs", "pua")
  end

  def test_convert_is_a_no_op_between_equal_modes
    marked = Textprov.mark(SOURCE, state: "ai", mode: "vs")

    assert_equal marked, Textprov.convert(marked, "vs", "vs")
  end

  def test_whitespace_is_never_marked
    marked = Textprov.mark("a b\tc\r\nd", state: "ai", mode: "vs")
    sel_cps = SELECTORS.values.to_set
    chars = marked.chars
    chars.each_with_index do |char, i|
      next unless char.match?(/\s/)

      after = chars[i + 1]

      refute (after && sel_cps.include?(after.ord)), "whitespace at #{i} was marked"
    end
  end

  def test_control_break_clusters_are_never_marked
    controls = "\x00\x1c\x7f\u00ad\u200b\ufeff\u2060\u2028\u2029\r\n"
    %w[vs pua].each do |mode|
      Textprov::GENERATED_STATES.each do |state|
        assert_equal controls, Textprov.mark(controls, state: state, mode: mode)
        source = "a" + controls + "b"
        marked = Textprov.mark(source, state: state, mode: mode)
        assert_equal marked, Textprov.mark(marked, state: state, mode: mode)
        assert_equal source, Textprov.strip_marks(marked)
        assert_equal [[state, "a"], [nil, controls], [state, "b"]], Textprov.runs(marked, strip: true)
        assert_equal source, Textprov.mark_added("ab", source, state: state, mode: mode)
      end
    end
  end

  def test_extending_format_characters_remain_markable
    ["a\u200c", FAMILY, "\u0600a", "\u{1f3f4 e0067 e007f}"].each do |cluster|
      assert_equal cluster + AI, Textprov.mark(cluster)
    end
  end

  def test_one_mark_per_cluster
    [FLAG, FAMILY, TONE, HEART, "é"].each do |cluster|
      assert_equal cluster + AI, Textprov.mark(cluster, state: "ai", mode: "vs"),
                   "cluster=#{cluster.inspect}"
      assert_equal cluster + AI, Textprov.mark(cluster, state: "ai", mode: "pua"),
                   "multi-code-point cluster has no PUA counterpart: #{cluster.inspect}"
      assert_equal cluster, Textprov.strip_marks(Textprov.mark(cluster, state: "ai", mode: "vs"))
    end
  end

  def test_marked_text_decodes_to_the_state_it_was_marked_with
    Textprov::GENERATED_STATES.each do |state|
      %w[vs pua].each do |mode|
        marked = Textprov.mark("Hi there", state: state, mode: mode)
        got = Textprov.runs(marked)

        assert_equal [state], got.map { |r| r[0] }, "state=#{state} mode=#{mode}"
      end
    end
  end
end

class TestMarkAdded < Minitest::Test
  def test_marks_only_the_middle
    assert_equal "abX#{AI}Y#{AI}c", Textprov.mark_added("abc", "abXYc")
  end

  def test_empty_old_text_marks_everything
    assert_equal Textprov.mark("ab", state: "ai", mode: "vs"), Textprov.mark_added("", "ab")
  end

  def test_unchanged_text_gains_no_marks
    assert_equal "abc", Textprov.mark_added("abc", "abc")
  end

  def test_state_and_mode_are_honoured
    assert_equal "abX#{HUMAN}", Textprov.mark_added("ab", "abX", state: "human")
    assert_equal "ab\u{100058}", Textprov.mark_added("ab", "abX", state: "ai", mode: "pua")
  end
end

class TestInspect < Minitest::Test
  def test_report_counts_states
    report = Textprov.inspect_text(Textprov.mark(SOURCE, state: "ai", mode: "vs"))

    assert_includes report, "ai_vs: 30"
    assert_includes report, "unmarked: 0"
  end

  def test_report_counts_unmarked_text
    report = Textprov.inspect_text("abc")

    assert_includes report, "unmarked: 3"
    assert_includes report, "ai_vs: 0"
    assert_includes report, "human: 0"
  end
end
