# python/tests/test_producer.py

"""Producer tests: the fixture's producer cases, plus the properties behind them.

A producer is pure text processing, so it is testable the same way a decoder
is. The recorded cases pin the output; the property tests say why those outputs
are the right ones.
"""

import json
import unittest
from pathlib import Path

import textprov

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = json.loads((ROOT / "fixtures.json").read_text(encoding="utf-8"))

AI = chr(textprov.default_mapping().selectors["ai"])
HUMAN = chr(textprov.default_mapping().selectors["human"])
FLAG = "\U0001f1e8\U0001f1e6"
FAMILY = "\U0001f468‍\U0001f469‍\U0001f467"
TONE = "\U0001f44d\U0001f3fd"
HEART = "❤️"
SOURCE = "Written by a human. Generated by AI."


class TestProducerFixtures(unittest.TestCase):
    def test_mark_cases(self):
        for case in FIXTURES["producer_cases"]:
            with self.subTest(case["name"]):
                self.assertEqual(
                    textprov.mark(case["input"], **case["options"]),
                    case["output"],
                )

    def test_convert_cases(self):
        for case in FIXTURES["convert_cases"]:
            with self.subTest(case["name"]):
                options = case["options"]
                self.assertEqual(
                    textprov.convert(
                        case["input"], options["from"], options["to"]
                    ),
                    case["output"],
                )


class TestProducerProperties(unittest.TestCase):
    """The properties a conforming producer must hold, per SPEC.md."""

    def test_strip_undoes_mark(self):
        for mode in ("vs", "pua"):
            for state in textprov.GENERATED_STATES:
                with self.subTest(mode=mode, state=state):
                    marked = textprov.mark(SOURCE, state, mode)
                    self.assertEqual(textprov.strip_marks(marked), SOURCE)

    def test_mark_is_idempotent(self):
        for mode in ("vs", "pua"):
            with self.subTest(mode=mode):
                once = textprov.mark(SOURCE, "ai", mode)
                self.assertEqual(textprov.mark(once, "ai", mode), once)

    def test_mark_does_not_touch_the_other_encoding(self):
        pua = textprov.mark(SOURCE, "ai", "pua")
        self.assertEqual(textprov.mark(pua, "ai", "vs"), pua)

    def test_pua_mode_equals_mark_then_convert(self):
        vs = textprov.mark(SOURCE, "ai", "vs")
        self.assertEqual(
            textprov.mark(SOURCE, "ai", "pua"),
            textprov.convert(vs, "vs", "pua"),
        )

    def test_convert_round_trips(self):
        vs = textprov.mark(SOURCE, "ai", "vs")
        pua = textprov.convert(vs, "vs", "pua")
        self.assertNotEqual(pua, vs)
        self.assertEqual(textprov.convert(pua, "pua", "vs"), vs)

    def test_convert_passes_other_states_through(self):
        marked = textprov.mark(SOURCE, "human", "vs")
        self.assertEqual(textprov.convert(marked, "vs", "pua"), marked)

    def test_convert_is_a_no_op_between_equal_modes(self):
        marked = textprov.mark(SOURCE, "ai", "vs")
        self.assertEqual(textprov.convert(marked, "vs", "vs"), marked)

    def test_whitespace_is_never_marked(self):
        marked = textprov.mark("a b\tc\r\nd", "ai", "vs")
        selectors = set(textprov.default_mapping().selectors.values())
        chars = list(marked)
        for index, char in enumerate(chars):
            if char.isspace():
                after = chars[index + 1] if index + 1 < len(chars) else ""
                self.assertFalse(
                    after and ord(after) in selectors,
                    f"whitespace at {index} was marked",
                )

    def test_one_mark_per_cluster(self):
        for cluster in (FLAG, FAMILY, TONE, HEART, "é"):
            with self.subTest(cluster=cluster):
                self.assertEqual(
                    textprov.mark(cluster, "ai", "vs"), cluster + AI
                )
                self.assertEqual(
                    textprov.mark(cluster, "ai", "pua"),
                    cluster + AI,
                    "a multi-code-point cluster has no PUA counterpart",
                )
                self.assertEqual(
                    textprov.strip_marks(textprov.mark(cluster, "ai", "vs")),
                    cluster,
                )

    def test_marked_text_decodes_to_the_state_it_was_marked_with(self):
        # The producer and the decoder are the two halves of one specification.
        for state in textprov.GENERATED_STATES:
            for mode in ("vs", "pua"):
                with self.subTest(state=state, mode=mode):
                    marked = textprov.mark("Hi there", state, mode)
                    self.assertEqual(
                        textprov.runs(marked),
                        [(state, textprov.runs(marked)[0][1])],
                    )
                    self.assertEqual(
                        [run[0] for run in textprov.runs(marked)], [state]
                    )


class TestMarkAdded(unittest.TestCase):
    def test_marks_only_the_middle(self):
        self.assertEqual(
            textprov.mark_added("abc", "abXYc"), "abX" + AI + "Y" + AI + "c"
        )

    def test_empty_old_text_marks_everything(self):
        self.assertEqual(
            textprov.mark_added("", "ab"), textprov.mark("ab", "ai", "vs")
        )

    def test_unchanged_text_gains_no_marks(self):
        self.assertEqual(textprov.mark_added("abc", "abc"), "abc")

    def test_state_and_mode_are_honoured(self):
        self.assertEqual(
            textprov.mark_added("ab", "abX", "human"), "abX" + HUMAN
        )
        self.assertEqual(
            textprov.mark_added("ab", "abX", "ai", "pua"), "ab\U00100058"
        )


class TestInspect(unittest.TestCase):
    def test_report_counts_states(self):
        report = textprov.inspect(textprov.mark(SOURCE, "ai", "vs"))
        self.assertIn("ai_vs: 30", report)
        self.assertIn("unmarked: 0", report)

    def test_report_counts_unmarked_text(self):
        report = textprov.inspect("abc")
        self.assertIn("unmarked: 3", report)
        self.assertIn("ai_vs: 0", report)
        self.assertIn("human: 0", report)
