#!/usr/bin/env python3
# tools/gen_grapheme_tables.py

"""Generate the grapheme-cluster property tables vendored by every port.

The three reference implementations segment text into extended grapheme
clusters (UAX #29) from the same tables, pinned to one Unicode version, so
they agree with each other and with GraphemeBreakTest.txt regardless of the
Unicode version their runtime happens to ship.

Usage:

    python3 tools/gen_grapheme_tables.py [--version 17.0.0] [--ucd DIR]

Reads GraphemeBreakProperty.txt, emoji-data.txt and DerivedCoreProperties.txt
from DIR (default tools/.ucd/<version>, downloaded from unicode.org when
missing) and writes:

    python/textprov/_ucd.py
    ruby/lib/textprov/ucd.rb
    js/textprov.js             (the block between the GENERATED markers)
    ucd/GraphemeBreakTest.txt  (the conformance file every port's tests read)

Each code point maps to one byte: the low four bits are its
Grapheme_Cluster_Break value, bit 4 is Extended_Pictographic, and bits 5-7
are the Indic_Conjunct_Break value. The table is a sorted list of the code
points where that byte changes, with the byte for each range beside it.
"""

import argparse
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

GCB = {
    "Other": 0,
    "CR": 1,
    "LF": 2,
    "Control": 3,
    "Extend": 4,
    "ZWJ": 5,
    "Regional_Indicator": 6,
    "Prepend": 7,
    "SpacingMark": 8,
    "L": 9,
    "V": 10,
    "T": 11,
    "LV": 12,
    "LVT": 13,
}
EXTENDED_PICTOGRAPHIC = 16
INCB = {"Consonant": 32, "Linker": 64, "Extend": 128}

FILES = {
    "GraphemeBreakProperty.txt": "ucd/auxiliary/GraphemeBreakProperty.txt",
    "GraphemeBreakTest.txt": "ucd/auxiliary/GraphemeBreakTest.txt",
    "emoji-data.txt": "ucd/emoji/emoji-data.txt",
    "DerivedCoreProperties.txt": "ucd/DerivedCoreProperties.txt",
}

LINE = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([^#;]+?)\s*(?:;\s*([^#]+?)\s*)?(?:#.*)?$")


def fetch(version, directory):
    directory.mkdir(parents=True, exist_ok=True)
    for name, remote in FILES.items():
        target = directory / name
        if target.exists():
            continue
        url = f"https://www.unicode.org/Public/{version}/{remote}"
        print(f"fetching {url}")
        with urllib.request.urlopen(url) as response:
            target.write_bytes(response.read())


def entries(path):
    """Yield (first, last, field1, field2) for every data line in a UCD file."""
    for line in path.read_text(encoding="utf-8").splitlines():
        match = LINE.match(line)
        if not match:
            continue
        first = int(match.group(1), 16)
        last = int(match.group(2), 16) if match.group(2) else first
        yield first, last, match.group(3), match.group(4)


def build(directory):
    table = bytearray(0x110000)
    for first, last, value, _ in entries(directory / "GraphemeBreakProperty.txt"):
        code = GCB[value]
        for cp in range(first, last + 1):
            table[cp] |= code
    for first, last, value, _ in entries(directory / "emoji-data.txt"):
        if value != "Extended_Pictographic":
            continue
        for cp in range(first, last + 1):
            table[cp] |= EXTENDED_PICTOGRAPHIC
    for first, last, value, second in entries(directory / "DerivedCoreProperties.txt"):
        if value != "InCB" or second == "None":
            continue
        for cp in range(first, last + 1):
            table[cp] |= INCB[second]
    bounds, codes = [0], [table[0]]
    for cp in range(1, 0x110000):
        if table[cp] != codes[-1]:
            bounds.append(cp)
            codes.append(table[cp])
    return bounds, codes


def header_version(path):
    """The Unicode version a UCD file declares in its header comment.

    Most files carry it in their first line, "# Name-17.0.0.txt"; emoji-data.txt
    carries "# Version: 17.0" instead and omits the patch number.
    """
    head = path.read_text(encoding="utf-8").splitlines()[:12]
    match = re.search(r"-(\d+\.\d+\.\d+)\.txt", head[0])
    if match:
        return match.group(1)
    for line in head:
        match = re.match(r"# Version: (\d+\.\d+)(\.\d+)?", line)
        if match:
            return match.group(1) + (match.group(2) or ".0")
    raise SystemExit(f"{path.name}: no Unicode version in header")


def wrap(items, indent, width=78):
    lines, current = [], indent
    for item in items:
        piece = item + ","
        if len(current) + len(piece) + 1 > width and current.strip():
            lines.append(current.rstrip())
            current = indent
        current += piece + " "
    if current.strip():
        lines.append(current.rstrip())
    return "\n".join(lines)


def notice(comment, version):
    return (
        f"{comment} Generated by tools/gen_grapheme_tables.py from Unicode {version}.\n"
        f"{comment} Do not edit by hand; rerun the generator to change the Unicode version.\n"
        f"{comment}\n"
        f"{comment} BOUNDS[i] is the first code point of range i; CODES[i] is its property\n"
        f"{comment} byte: bits 0-3 Grapheme_Cluster_Break (see GCB), bit 4\n"
        f"{comment} Extended_Pictographic, bits 5-7 Indic_Conjunct_Break (see INCB).\n"
    )


def write_python(version, bounds, codes):
    path = ROOT / "python" / "textprov" / "_ucd.py"
    text = (
        "# python/textprov/_ucd.py\n\n"
        + notice("#", version)
        + "\n"
        + f'UNICODE_VERSION = "{version}"\n\n'
        + "GCB = " + python_dict(GCB) + "\n"
        + f"EXTENDED_PICTOGRAPHIC = {EXTENDED_PICTOGRAPHIC}\n"
        + "INCB = " + python_dict(INCB) + "\n\n"
        + "BOUNDS = [\n" + wrap([hex(b) for b in bounds], "    ") + "\n]\n\n"
        + "CODES = [\n" + wrap([str(c) for c in codes], "    ") + "\n]\n"
    )
    path.write_text(text, encoding="utf-8")
    return path


def python_dict(mapping):
    inner = ", ".join(f'"{key}": {value}' for key, value in mapping.items())
    return "{" + inner + "}"


def write_ruby(version, bounds, codes):
    path = ROOT / "ruby" / "lib" / "textprov" / "ucd.rb"
    text = (
        "# ruby/lib/textprov/ucd.rb\n#\n# frozen_string_literal: true\n\n"
        + notice("#", version)
        + "\nmodule Textprov\n  module UCD\n"
        + f'    UNICODE_VERSION = "{version}"\n\n'
        + "    GCB = " + ruby_hash(GCB) + ".freeze\n"
        + f"    EXTENDED_PICTOGRAPHIC = {EXTENDED_PICTOGRAPHIC}\n"
        + "    INCB = " + ruby_hash(INCB) + ".freeze\n\n"
        + "    BOUNDS = [\n" + wrap([hex(b) for b in bounds], "      ") + "\n    ].freeze\n\n"
        + "    CODES = [\n" + wrap([str(c) for c in codes], "      ") + "\n    ].freeze\n"
        + "  end\nend\n"
    )
    path.write_text(text, encoding="utf-8")
    return path


def ruby_hash(mapping):
    inner = ", ".join(f'"{key}" => {value}' for key, value in mapping.items())
    return "{" + inner + "}"


def write_javascript(version, bounds, codes):
    path = ROOT / "js" / "textprov.js"
    source = path.read_text(encoding="utf-8")
    begin = "  // BEGIN GENERATED"
    end = "  // END GENERATED"
    start = source.index(begin)
    stop = source.index(end) + len(end)
    block = (
        begin
        + "\n"
        + notice("  //", version)
        + f'  var UNICODE_VERSION = "{version}";\n'
        + "  var GCB = " + js_object(GCB) + ";\n"
        + f"  var EXTENDED_PICTOGRAPHIC = {EXTENDED_PICTOGRAPHIC};\n"
        + "  var INCB = " + js_object(INCB) + ";\n"
        + "  var BOUNDS = [\n" + wrap([hex(b) for b in bounds], "    ") + "\n  ];\n"
        + "  var CODES = [\n" + wrap([str(c) for c in codes], "    ") + "\n  ];\n"
        + end
    )
    path.write_text(source[:start] + block + source[stop:], encoding="utf-8")
    return path


def js_object(mapping):
    inner = ", ".join(f"{key}: {value}" for key, value in mapping.items())
    return "{ " + inner + " }"


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--version", default="17.0.0", help="Unicode version to pin")
    parser.add_argument("--ucd", type=Path, help="directory holding the UCD files")
    args = parser.parse_args()
    directory = args.ucd or ROOT / "tools" / ".ucd" / args.version
    fetch(args.version, directory)
    for name in FILES:
        found = header_version(directory / name)
        if found != args.version:
            raise SystemExit(f"{name} is Unicode {found}, expected {args.version}")
    bounds, codes = build(directory)
    written = [
        write_python(args.version, bounds, codes),
        write_ruby(args.version, bounds, codes),
        write_javascript(args.version, bounds, codes),
    ]
    test = ROOT / "ucd" / "GraphemeBreakTest.txt"
    test.parent.mkdir(exist_ok=True)
    test.write_bytes((directory / "GraphemeBreakTest.txt").read_bytes())
    written.append(test)
    for path in written:
        print(f"wrote {path.relative_to(ROOT)}")
    print(f"{len(bounds)} ranges")


if __name__ == "__main__":
    main()
